version: '3.7'

services:
  snippet-manager-api:
    container_name: snippet-manager-api
    image: ghcr.io/snippet-searcher-austral/snippet-manager-prod:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-manager-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/snippet-manager.env
      - env-files/datadog-sub.env

  snippet-manager_db:
    container_name: snippet-manager_db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/snippet-manager-db.env
    volumes:
      - snippet-manager:/var/lib/postgresql/data

  authorizer-api:
    container_name: authorizer-api
    image: ghcr.io/snippet-searcher-austral/authorizer-prod:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "authorizer-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/authorizer.env
      - env-files/datadog-sub.env

  authorizer_db:
    container_name: authorizer-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/authorizer-db.env
    volumes:
      - authorizer:/var/lib/postgresql/data

  formatter-api:
    container_name: formatter-api
    image: ghcr.io/snippet-searcher-austral/formatter-prod:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "formatter-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/formatter.env
      - env-files/datadog-sub.env

  formatter-db:
    container_name: formatter-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/formatter-db.env
    volumes:
      - formatter:/var/lib/postgresql/data

  linter-api:
    container_name: linter-api
    image: ghcr.io/snippet-searcher-austral/linter-prod:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "linter-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/linter.env
      - env-files/datadog-sub.env

  linter-db:
    container_name: linter-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/linter-db.env

  executor-api:
    container_name: executor-api
    image: ghcr.io/snippet-searcher-austral/executor-prod:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "executor-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/executor.env
      - env-files/datadog-sub.env

  datadog:
    image: datadog/agent
    container_name: "datadog-prod"
    hostname: 'datadog-prod'
    env_file:
      - env-files/datadog.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./conf.d:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "proxy", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/datadog-sub.env

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - '6379:6379'
  app:
    container_name: app
    image: ghcr.io/snippet-searcher-austral/app-prod:latest
    env_file:
      - env-files/app.env


volumes:
  snippet-manager:
  authorizer:
  linter:
  formatter: