version: '3.7'

services:
  snippet-manager-api:
    container_name: snippet-manager-api
    image: ghcr.io/snippet-searcher-austral/snippet-manager-dev:latest
    #    ports:
    #      - '8080:8080'
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-manager-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/snippet-manager.env
      - env-files/datadog-sub.env

  snippet-manager_db:
    container_name: snippet-manager_db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/snippet-manager-db.env
      - env-files/datadog-sub.env

    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-manager-db", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

    volumes:
      - snippet-manager:/var/lib/postgresql/data
  authorizer-api:
    container_name: authorizer-api
    image: ghcr.io/snippet-searcher-austral/authorizer-dev:latest
    #    ports:
    #      - '8081:8080'
    env_file:
      - env-files/authorizer.env
      - env-files/datadog-sub.env
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "authorizer-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  authorizer_db:
    container_name: authorizer-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/authorizer-db.env
      - env-files/datadog-sub.env
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "authorizer-db", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

    volumes:
      - authorizer:/var/lib/postgresql/data
  parser-api:
    container_name: parser-api
    image: ghcr.io/snippet-searcher-austral/parser-dev:latest
    env_file:
      - env-files/datadog-sub.env
  #    ports:
  #      - '8083:8080'
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "parser-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  formatter-api:
    container_name: formatter-api
    image: ghcr.io/snippet-searcher-austral/formatter-dev:latest
    env_file:
      - env-files/datadog-sub.env
  #    ports:
  #      - '8084:8080'
    labels:
     com.datadoghq.ad.logs: '[{"source": "java", "service": "formatter-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  linter-api:
    container_name: linter-api
    image: ghcr.io/snippet-searcher-austral/linter-dev:latest
    #    ports:
    #      - '8085:8080'
    env_file:
      - env-files/linter.env
      - env-files/datadog-sub.env
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "linter-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  linter-db:
    container_name: linter-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/linter-db.env
      - env-files/datadog-sub.env
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "linter-db", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  executor-api:
    container_name: executor-api
    image: ghcr.io/snippet-searcher-austral/executor-dev:latest
    env_file:
      - env-files/datadog-sub.env
  #    ports:
  #      - '8086:8080'
    labels:
     com.datadoghq.ad.logs: '[{"source": "java", "service": "executor-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  datadog:
    image: datadog/agent
    container_name: "datadog-dev"
    hostname: 'datadog-dev'
    env_file:
        - env-files/datadog.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./conf-test.d:/etc/nginx/conf.d/:ro
    env_file:
      - env-files/datadog-sub.env
    labels:
     com.datadoghq.ad.logs: '[{"source": "java", "service": "proxy", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - '6379:6379'

volumes:
  snippet-manager:
  authorizer:
  linter: