version: '3.7'

services:
  snippet-manager-api:
    container_name: snippet-manager-api
    image: ghcr.io/snippet-searcher-austral/snippet-manager-dev:latest
#    ports:
#      - '8080:8080'
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "snippet-manager-api", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    env_file:
      - env-files/snippet-manager.env
  snippet-manager_db:
    container_name: snippet-manager_db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/snippet-manager-db.env
    volumes:
      - snippet-manager:/var/lib/postgresql/data
  authorizer-api:
    container_name: authorizer-api
    image: ghcr.io/snippet-searcher-austral/authorizer-dev:latest
#    ports:
#      - '8081:8080'
    env_file:
      - env-files/authorizer.env
  authorizer_db:
    container_name: authorizer-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/authorizer-db.env
    volumes:
      - authorizer:/var/lib/postgresql/data
  parser-api:
    container_name: parser-api
    image: ghcr.io/snippet-searcher-austral/parser-dev:latest
#    ports:
#      - '8083:8080'
  formatter-api:
    container_name: formatter-api
    image: ghcr.io/snippet-searcher-austral/formatter-dev:latest
#    ports:
#      - '8084:8080'
  linter-api:
    container_name: linter-api
    image: ghcr.io/snippet-searcher-austral/linter-dev:latest
#    ports:
#      - '8085:8080'
    env_file:
      - env-files/linter.env
  linter-db:
    container_name: linter-db
    image: postgres:12
    ports:
      - '5432'
    env_file:
      - env-files/linter-db.env
  executor-api:
    container_name: executor-api
    image: ghcr.io/snippet-searcher-austral/executor-dev:latest
#    ports:
#      - '8086:8080'
  datadog:
    image: datadog/agent
    container_name: "datadog-dev-env"
    hostname: 'datadog-dev'
    environment:
      - DD_API_KEY=656265fadc999c8a5501d14705af6619
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_HOSTNAME=datadog-dev
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./conf.d:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  snippet-manager:
  authorizer:
  linter: