version: '3.7'

services:
  snippet-manager-api:
    container_name: snippet-manager-api
    image: ghcr.io/snippet-searcher-austral/snippet-manager-prod:latest
    ports:
      - '8080:8080'
    env_file:
      - snippet-manager.env
  snippet-manager_db:
    container_name: snippet-manager_db
    image: postgres:12
    ports:
      - '5432:5432'
    env_file:
      - snippet-manager-db.env
    volumes:
      - snippet-manager:/var/lib/postgresql/data
  snippet-authorizer-api:
    container_name: snippet-authorizer-api
    image: ghcr.io/snippet-searcher-austral/authorizer-prod:latest
    ports:
      - '8081:8080'
    env_file:
      - authorizer.env
  snippet_authorizer_db:
    container_name: snippet_authorizer_db
    image: postgres:12
    ports:
      - '5433:5432'
    env_file:
      - authorizer-database.env
    volumes:
      - snippet-authorizer:/var/lib/postgresql/data
  snippet-parser-api:
    container_name: snippet-parser-api
    image: ghcr.io/snippet-searcher-austral/snippet-parser-prod:latest
    ports:
      - '8083:8080'
    env_file:
      - parser.env
  snippet-formatter-api:
    container_name: snippet-parser-api
    image: ghcr.io/snippet-searcher-austral/snippet-formatter-prod:latest
    ports:
      - '8084:8080'
    env_file:
      - formatter.env
  snippet-linter-api:
    container_name: snippet-parser-api
    image: ghcr.io/snippet-searcher-austral/snippet-linter-prod:latest
    ports:
      - '8085:8080'
    env_file:
      - linter.env
  snippet-executor-api:
    container_name: snippet-parser-api
    image: ghcr.io/snippet-searcher-austral/snippet-executor-prod:latest
    ports:
      - '8086:8080'
    env_file:
      - executor.env

volumes:
  snippet-manager:
  snippet-authorizer: