name: Deploy test to Dev Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 400 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.DEV_SSH_PRIVATE}}
          SSH_KNOWN_HOSTS: ${{secrets.DEV_SSH_KNOWN_HOSTS}}
      - name: Print Current Directory
        run: |
          pwd
          ls
      - name: Connect via SSH and deploy
        run: |
          scp -i $SSH_KEY_PATH src/docker-compose-test.yml matito@${{secrets.DEV_SSH_HOST}}:~/docker-compose.yml
          ssh -i $SSH_KEY_PATH matito@${{secrets.DEV_SSH_HOST}} "sudo bash -s" <<EOF
            bash ~/deploy-script.sh "all"
          EOF
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
